src/Entity/TV.php
<?php

namespace App\Entity;

use App\Repository\TVRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TVRepository::class)]
class TV
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $tv_code = null;

    #[ORM\Column(length: 255)]
    private ?string $screen_size = null;

    #[ORM\Column]
    private ?bool $smarttv = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fabdate = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\ManyToOne(inversedBy: 'tVs')]
    private ?Shop $shop = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTvCode(): ?string
    {
        return $this->tv_code;
    }

    public function setTvCode(string $tv_code): static
    {
        $this->tv_code = $tv_code;

        return $this;
    }

    public function getScreenSize(): ?string
    {
        return $this->screen_size;
    }

    public function setScreenSize(string $screen_size): static
    {
        $this->screen_size = $screen_size;

        return $this;
    }

    public function isSmarttv(): ?bool
    {
        return $this->smarttv;
    }

    public function setSmarttv(bool $smarttv): static
    {
        $this->smarttv = $smarttv;

        return $this;
    }

    public function getFabdate(): ?\DateTimeInterface
    {
        return $this->fabdate;
    }

    public function setFabdate(\DateTimeInterface $fabdate): static
    {
        $this->fabdate = $fabdate;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): static
    {
        $this->shop = $shop;

        return $this;
    }
}

src/Form/TvType.php
<?php

namespace App\Form;

use App\Entity\Shop;
use App\Entity\TV;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TvType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('tv_code')
            ->add('screen_size')
            ->add('smarttv')
            ->add('fabdate', null, [
                'widget' => 'single_text',
            ])
            ->add('price')
            ->add('shop', EntityType::class, [
                'class' => Shop::class,
                'choice_label' => 'id',
                'multiple' => false,
                'expanded' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TV::class,
        ]);
    }
}

src/Controller/TvController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\TVRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\TvType;
use App\Entity\TV;
use Doctrine\Persistence\ManagerRegistry;

#[Route('/tv')]
class TvController extends AbstractController
{
    #[Route('/test', name: 'app_tv')]
    public function index(): Response
    {
        return $this->render('tv/index.html.twig', [
            'controller_name' => 'TVController',
        ]);
    }

    #[Route('/display', name:"app_display")]
    public function display(TVRepository $rep): Response
    {

        $tvs = $rep->findAll();
        return $this->render('tv/display.html.twig', [
            'tvs' => $tvs,
        ]);
    }
    
    #[Route('/update/{id}', name: 'update_tv')]
public function updateTV(ManagerRegistry $doctrine, Request $request, TVRepository $rep, $id): Response
{
    $em = $doctrine->getManager();
    $tv = $rep->find($id);

    if (!$tv) {
        throw $this->createNotFoundException('No tv found for id ' . $id);
    }

    $form = $this->createForm(TvType::class, $tv);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $em->flush();
        return $this->redirectToRoute('app_display');
    }

    return $this->render('tv/update.html.twig', [
        'form' => $form->createView(),
    ]);
}

}

templates/tv/display.html.twig
<h1>Tableau tv</h1>
  
  <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>code</th>
                <th>screen size</th>
                <th>smart</th>
                <th>fabrication date</th>
                <th>Price</th>
                <th>links</th>
            </tr>
        </thead> 
        <tbody>
            {% for tv in tvs %}
                <tr>
                    <td>{{ tv.id }}</td>
                    <td>{{ tv.tvCode }}</td>
                    <td>{{ tv.screenSize }}</td>
                    <td>{{ tv.smarttv }}</td>
                    <td>{{ tv.fabdate|date('d-m-Y')}}</td>
                    <td>{{ tv.price }}</td>
                    <td>
                        <a href="/tv/update/{{ tv.id }}">Update</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

templates/tv/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TvController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/xampp/htdocs/FirstProject/src/Controller/TvController.php</code></li>
        <li>Your template at <code>C:/xampp/htdocs/FirstProject/templates/tv/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/tv/update.html.twig
<h1>Update Author</h1>

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit">Update</button>
{{ form_end(form) }}