src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?bool $enabled = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $pubdate = null;

    #[ORM\ManyToOne(inversedBy: 'books')]
    private ?Author $Authorid = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): static
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function getPubdate(): ?\DateTimeInterface
    {
        return $this->pubdate;
    }

    public function setPubdate(\DateTimeInterface $pubdate): static
    {
        $this->pubdate = $pubdate;

        return $this;
    }

    public function getAuthorid(): ?Author
    {
        return $this->Authorid;
    }

    public function setAuthorid(?Author $Authorid): static
    {
        $this->Authorid = $Authorid;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Book;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('enabled')
            ->add('pubdate', null, [
                'widget' => 'single_text',
            ])
            ->add('Authorid', EntityType::class, [
                'class' => Author::class,
                'choice_label' => 'id',
                'multiple' => false,
                'expanded' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\BookRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\BookType;
use App\Entity\Book;
use Doctrine\Persistence\ManagerRegistry;

#[Route('book')]
class BookController extends AbstractController
{
    #[Route('/Book', name: 'app_Book')]
    public function index(): Response
    {
        return $this->render('Book/index.html.twig', [
            'controller_name' => 'BookController',
        ]);
    }

    #[Route('/display', name:"app_display_book")]
    public function displayBooks(BookRepository $rep): Response
    {
        #$books = $entityManager->getRepository(Book::class)->findAll();
        $books = $rep->findAll();
        return $this->render('book/display.html.twig', [
            'books' => $books,
        ]);
    }

    #[Route('/delete/{id}', name:"delete_book")]
    public function deleteBooks(BookRepository $rep , $id, EntityManagerInterface $em): Response
    {
        $book = $rep->find($id);

        $em->remove($book);
        $em->flush();
        return $this->redirectToRoute("app_display_book");
    }

    #[Route('/add', name:"add_book")]
    public function addBook(ManagerRegistry $doctrine, Request $request): Response
    {
        $em = $doctrine->getManager();
        $book = new book(); 
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($book);
            $em->flush();
            
        return $this->redirectToRoute("app_display_book");
        
        }

        return $this->render('book/add.html.twig', [
            'f' => $form
        ]);
    }
}

templates/book/add.html.twig
<h1>Add a book</h1>

{{ form_start(f) }}
    {{ form_widget(f) }}
    <button type="submit">Submit</button>
{{ form_end(f) }}

templates/book/display.html.twig
<h1> book list</h1>
{{dump(books)}}

<h1>Tableau</h1>
  
  <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>title</th>
                <th>enabled</th>
                <th>Author</th>
                <th>date</th>
                <th>links</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.id }}</td>
                    <td>{{ book.title}}</td>
                    <td>{{ book.enabled ? "Yes" : "No" }}</td>
                    <td>{% if book.authorid %}
                        {{ book.authorid.username }}
                    {% else %}
                        Autheur inconnu
                    {% endif %}
                    </td>
                    <td>{{ book.pubdate|date('d-m-Y')}}</td>
                    <td>
                        <a href="book/update">update</a>
                        <a href="/delete/{{ book.id }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/xampp/htdocs/FirstProject/src/Controller/BookController.php</code></li>
        <li>Your template at <code>C:/xampp/htdocs/FirstProject/templates/book/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}